"""app/tools/formatting.py

Formatting utilities for the School AI Assistant.

Produces structured envelopes for user-facing responses and lesson plan templates.
"""

from datetime import datetime, timezone
from app.app_utils.logging_config import get_logger

logger = get_logger(__name__)


def format_response(content: str, role: str = "unknown") -> dict:
    """Wrap agent text in a structured response envelope with metadata.

    Args:
        content: The response text generated by the agent.
        role: The role classification for the response tone ("parent", "teacher", "unknown").

    Returns:
        dict: Keys are:
            - 'role' (str): The cleaned role string.
            - 'content' (str): The response text.
            - 'formatted_at' (str): ISO 8601 UTC timestamp.
            - 'word_count' (int): Total words in the content.
    """
    logger.info("event=format_response_started | role=%s", role)
    words = content.split()
    word_count = len(words)

    result = {
        "role": role.strip().lower(),
        "content": content,
        "formatted_at": datetime.now(timezone.utc).isoformat(),
        "word_count": word_count,
    }
    logger.info("event=format_response_completed | word_count=%d", word_count)
    return result


def format_lesson_plan(
    topic: str,
    grade_level: int,
    duration_minutes: int = 45,
    subject: str = "",
) -> dict:
    """Generate a structured lesson plan scaffold for a given topic.

    The time allocation breakdown is calculated proportionally to duration_minutes
    and is guaranteed to sum to the total duration.

    Args:
        topic: The lesson topic (e.g. 'Photosynthesis', 'Fractions').
        grade_level: The student grade level (1 to 12).
        duration_minutes: Total class duration in minutes (default 45).
        subject: The school subject (e.g. 'Science', 'Mathematics').

    Returns:
        dict: Keys are:
            - 'topic' (str): The lesson topic.
            - 'grade_level' (int): Clamped grade level [1, 12].
            - 'subject' (str): The school subject.
            - 'duration_minutes' (int): Total class duration in minutes.
            - 'sections' (dict): The empty structural sections for the agent to populate, including:
                - 'learning_objectives' (str): Bloom's Taxonomy objectives placeholder.
                - 'materials' (str): Required resources placeholder.
                - 'teaching_activities' (str): Step-by-step procedure placeholder.
                - 'assessment' (str): Check for understanding placeholder.
                - 'homework' (str): Reinforcement activity placeholder.
                - 'time_allocation' (dict): Calculated time allocations in minutes.
    """
    logger.info(
        "event=format_lesson_plan_started | topic=%s | grade=%d | duration=%d",
        topic,
        grade_level,
        duration_minutes,
    )

    # Clamp grade level to 1-12 range
    clamped_grade = max(1, min(12, grade_level))

    # Proportional time allocation calculation (relative to 45 mins model)
    intro = max(1, round(duration_minutes * 5 / 45))
    direct = max(1, round(duration_minutes * 15 / 45))
    guided = max(1, round(duration_minutes * 10 / 45))
    independent = max(1, round(duration_minutes * 10 / 45))
    wrap = max(1, duration_minutes - (intro + direct + guided + independent))

    time_alloc = {
        "introduction_hook": f"{intro} minutes",
        "direct_instruction": f"{direct} minutes",
        "guided_practice": f"{guided} minutes",
        "independent_practice_activity": f"{independent} minutes",
        "assessment_wrap_up": f"{wrap} minutes",
    }

    result = {
        "topic": topic,
        "grade_level": clamped_grade,
        "subject": subject.strip() or "General",
        "duration_minutes": duration_minutes,
        "sections": {
            "learning_objectives": "[To be completed by agent using Bloom's Taxonomy verbs]",
            "materials": "[To be completed by agent with required resources/tools]",
            "teaching_activities": "[To be completed by agent with procedure]",
            "assessment": "[To be completed by agent with formative checks]",
            "homework": "[To be completed by agent with homework task]",
            "time_allocation": time_alloc,
        },
    }

    logger.info("event=format_lesson_plan_completed | status=success")
    return result
